### ISSUE TITLE
Backward pass is invalid for module in evaluation mode during minillm training with ZeRO parameter offload

### ISSUE THREAD

**Issue by Ispanicus** [microsoft/LMOps#128]
Hi, I'm experiencing an Assertion Error during training of miniLLM using ZeRO with optimizer and parameter offload on a single H100 GPU. It seems as though deepspeed's parameter offload script is getting the model in evaluation mode during training.

Here is the stack trace:
```
LM Evaluation: 100%|██████████| 500/500 [05:16<00:00,  1.58it/s]
Traceback (most recent call last):
  File "/dtu/p1/alaisp/LMOps/minillm/train_minillm.py", line 93, in <module>
    main()
  File "/dtu/p1/alaisp/LMOps/minillm/train_minillm.py", line 79, in main
    train(
  File "/dtu/p1/alaisp/LMOps/minillm/minillm/__init__.py", line 51, in train
    trainer.train()
  File "/dtu/p1/alaisp/LMOps/minillm/minillm/trainer.py", line 287, in train
    self.model.backward(loss)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1895, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 2041, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/torch/autograd/function.py", line 288, in apply
    return user_fn(self, *args)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 169, in backward
    ctx.pre_backward_function(ctx.module)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 435, in _run_before_backward_function
    self.pre_sub_module_backward_function(sub_module)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/zhome/94/6/208806/.local/lib/python3.9/site-packages/deepspeed/runtime/zero/parameter_offload.py", line 511, in pre_sub_module_backward_function
    assert sub_module.training, "backward pass is invalid for module in evaluation mode"
AssertionError: backward pass is invalid for module in evaluation mode
```

Any help provided in resolving the issue will be much appreciated!

**Comment by t1101675** [comment]
Thanks for your attention to our work! 

This error is caused by DeepSpeed-zero3 (They do not support backward in an evaluation mode). We need the eval mode because the MiniLLM training is similar to the RL training where dropout is usually not applied. 

If you use zero3 because of insufficient GPU memory, you can try using [zero-offload](https://www.deepspeed.ai/tutorials/zero-offload/) by setting the DeepSpeed config to the [corresponding path](https://github.com/microsoft/LMOps/blob/803f834779bc419c3011c9ef0d3cdb2d328b4b14/minillm/scripts/llama/sft/sft_7B_mn.sh#L73) .
If you insist on using zero3, you can set the dropout value to 0 in the model config files before running the script and add `self.model.train()` before every step (for example, at this [line](https://github.com/microsoft/LMOps/blob/803f834779bc419c3011c9ef0d3cdb2d328b4b14/minillm/minillm/trainer.py#L254)). In this way, you can avoid using dropout and do backward with the training mode at the same time.

**Comment by Ispanicus** [comment]
I was using your deepspeed config file for zero2 offload, which I changed to zero3 and added parameter offload. If I understand you correctly, optimizer offload with zero2 works, but adding parameter offload and using zero3 is not yet implemented?

Which model config file are you referring to exactly which contains the dropout value?

I managed to run llama7B_13B minillm with zero2 on a single H100 GPU by reducing the max sequence length to 256. In your opinion, will this degrade performance significantly?

Thank you for your help!

**Comment by t1101675** [comment]
>I was using your deepspeed config file for zero2 offload, which I changed to zero3 and added parameter offload. If I understand you correctly, optimizer offload with zero2 works, but adding parameter offload and using zero3 is not yet implemented?

Yes.

The "model config file" refers to the huggingface config files in the checkpoint directory you load from.

I think reducing the max sequence length to 256 will mainly affect the performance of long instructions/responses. On short instructions, the performance will not be affected much.

**Comment by Ispanicus** [comment]
Alright, thank you for your help!
