### ISSUE TITLE
Uprise: load persistent id instruction was encountered

### ISSUE THREAD

**Issue by dittops** [microsoft/LMOps#94]
I'm trying to run the generate_dense_embeddings script with the following command

```
python DPR/generate_dense_embeddings.py  model_file=/root/LMOps/uprise/archive/data.pkl  ctx_src=dpr_uprise shard_id=0 num_shards=1  out_file=$PWD/my_data/experiment/uprise/dpr_enc_index  ctx_sources.dpr_uprise.prompt_pool_path=${PROMPT_POOL}  ctx_sources.dpr_uprise.prompt_setup_type=qa  encoder.cache_dir=${CACHE_DIR}  hydra.run.dir=$PWD/my_data/experiment/uprise
```

But I'm getting the below error.

```
[2023-10-17 13:48:09,195][root][INFO] - Reading saved model from /root/LMOps/uprise/archive/data.pkl
Error executing job with overrides: ['model_file=/root/LMOps/uprise/archive/data.pkl', 'ctx_src=dpr_uprise', 'shard_id=0', 'num_shards=1', 'out_file=/root/LMOps/uprise/my_data/experiment/uprise/dpr_enc_index', 'ctx_sources.dpr_uprise.prompt_pool_path=prompt_pool.json', 'ctx_sources.dpr_uprise.prompt_setup_type=qa', 'encoder.cache_dir=cache/']
Traceback (most recent call last):
  File "DPR/generate_dense_embeddings.py", line 106, in main
    saved_state = load_states_from_checkpoint(cfg.model_file)
  File "/root/LMOps/uprise/DPR/dpr/utils/model_utils.py", line 170, in load_states_from_checkpoint
    state_dict = torch.load(
  File "/root/LMOps/uprise/.env/lib/python3.8/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/LMOps/uprise/.env/lib/python3.8/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.
```

**Comment by cdxeve** [comment]
Hi, did you download the model file  ("/root/LMOps/uprise/archive/data.pkl") from our path (https://drive.google.com/file/d/1fd6wYiP8LMRfM1f2oiFSn4t5jb_xLuo-/view?usp=share_link)?

**Comment by dittops** [comment]
yes, I have downloaded the model from that path.

**Comment by cdxeve** [comment]
The original file is named as retriever_ckpt, how about removing the ".pkl" suffix to avoid loading it via pickle? and maybe you can check if this file is a complete version of the downloaded one.

**Comment by dittops** [comment]
Directly using the downloaded file without .pkl suffix resolved the issue. Thanks for your support.
