### ISSUE TITLE
Issue with using minillm for distilling models with different d_model.

### ISSUE THREAD

**Issue by TanayNarshana** [microsoft/LMOps#99]
Hello!

Thank you for open sourcing this amazing work. We are trying to distill encoder-decoder architectures like flan-t5 using minillm. However, we are facing the following issue when distilling flan-t5-xl to flan-t5-large.

```
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/train_minillm.py", line 109, in <module>
    main()
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/train_minillm.py", line 95, in main
    train(
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/minillm/__init__.py", line 37, in train
    sampler.run_sample(args.num_rollouts)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/minillm/sampler.py", line 71, in run_sample
    gen_out = self.trainer.generate(**batch, return_dict_in_generate=True, mode=mode, teacher_mixed_sample=(self.args.teacher_mixed_alpha is not None), output_scores=True)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/minillm/trainer.py", line 620, in generate
    gen = model.generate(
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/minillm/model.py", line 29, in generate
    return self.base_model.generate(**x)
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/generation/utils.py", line 1580, in generate
    return self.sample(
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/generation/utils.py", line 2704, in sample
    m_outputs = mix_in_model(
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/models/t5/modeling_t5.py", line 1720, in forward
    decoder_outputs = self.decoder(
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/models/t5/modeling_t5.py", line 1090, in forward
    layer_outputs = layer_module(
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/models/t5/modeling_t5.py", line 723, in forward
    cross_attention_outputs = self.layer[1](
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/models/t5/modeling_t5.py", line 634, in forward
    attention_output = self.EncDecAttention(
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/models/t5/modeling_t5.py", line 522, in forward
    key_states = project(
  File "/home/ec2-user/SageMaker/tanayn/llm-exploration/knowledge-distillation/minillm/transformers/src/transformers/models/t5/modeling_t5.py", line 500, in project
    hidden_states = shape(proj_layer(key_value_states))
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x1024 and 2048x2048)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 11072) of binary: /home/ec2-user/SageMaker/tanayn/kd/bin/python3.10
Traceback (most recent call last):
  File "/home/ec2-user/SageMaker/tanayn/kd/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ec2-user/SageMaker/tanayn/kd/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

I believe this is happening since the d_model size for both the models differ (1024 for flan-t5-large and 2048 for flan-t5-xl).

So, I have two questions.
1. Can we distill models from the same family but different d_model sizes? If so, what would be a way to fix this error?
2. Does the code support distilling encoder-decoder models using minillm? Or are there some challenges that the authors foresee in doing so?

**Comment by t1101675** [comment]
1. Yes. We can distill models with different d_model sizes. The error is because our code does not support encoder-decoder models yet. The error is caused by using the same `encoder_outputs` to the student and teacher model, which will not happen to decoder-only models (they don't have `encoder_outputs`).
2. Distilling encoder-decoder models is not challenging in principle. However, since our code is mainly designed for decoder-only language models, supporting encoder-decoder models may need some work to reformulate the code. Maybe we will add this as a future plan, but contributions are welcome!
